version: 2

# 语义模型定义
semantic_models:
  - name: toll_revenue_semantic_model
    description: "收费收入语义模型，基于日收费收入汇总表"
    model: ref('dws_toll_revenue_daily')
    
    # 默认配置
    defaults:
      agg_time_dimension: transaction_date
    
    # 定义实体（Entities）- 用于关联和分组
    entities:
      - name: transaction
        type: primary
        expr: transaction_date || '_' || station_id  # 组合键作为主实体
    
    # 定义度量（Measures）- 可聚合的数值字段
    measures:
      - name: total_revenue
        description: "总收入"
        agg: sum
        expr: total_actual_amount
        label: "总收入（元）"
        
      - name: transaction_count
        description: "交易笔数"
        agg: sum
        expr: transaction_count
        label: "交易笔数"
        
      - name: vehicle_count
        description: "车辆数"
        agg: sum
        expr: vehicle_count
        label: "车辆数"
        
      - name: normal_transaction_count
        description: "正常交易数"
        agg: sum
        expr: normal_transaction_count
        label: "正常交易数"
        
      - name: abnormal_transaction_count
        description: "异常交易数"
        agg: sum
        expr: abnormal_transaction_count
        label: "异常交易数"
        
      - name: avg_transaction_amount
        description: "平均交易金额"
        agg: average
        expr: avg_transaction_amount
        label: "平均交易金额（元）"
        
      - name: quality_normal_count
        description: "数据质量正常记录数"
        agg: sum
        expr: quality_normal_count
        label: "质量正常记录数"
    
    # 定义维度（Dimensions）- 用于分组和过滤的字段
    dimensions:
      - name: transaction_date
        type: time
        type_params:
          time_granularity: day
        label: "交易日期"
        description: "交易日期，支持按日、周、月、年聚合"
        
      - name: city
        type: categorical
        label: "城市"
        description: "收费站所在城市"
        
      - name: station_name
        type: categorical
        label: "收费站名称"
        description: "收费站名称"
        
      - name: station_id
        type: categorical
        label: "收费站ID"
        description: "收费站唯一标识"
        
      - name: vehicle_type_name
        type: categorical
        label: "车型名称"
        description: "车辆类型名称"
        
      - name: payment_method_name
        type: categorical
        label: "支付方式"
        description: "支付方式名称"
        
      - name: highway_code
        type: categorical
        label: "高速公路编码"
        description: "高速公路编码"
        
      - name: station_type
        type: categorical
        label: "收费站类型"
        description: "主线收费站或匝道收费站"

models:
  - name: dws_toll_revenue_daily
    description: "日收费收入汇总，按日期、收费站、车型、支付方式等维度汇总"
    columns:
      - name: transaction_date
        description: "交易日期"
        meta:
          column_name_cn: "交易日期"
      - name: station_id
        description: "收费站ID"
        meta:
          column_name_cn: "收费站ID"
      - name: total_actual_amount
        description: "日实收金额汇总（元）"
        meta:
          column_name_cn: "日实收金额"
      - name: transaction_count
        description: "交易笔数"
        meta:
          column_name_cn: "交易笔数"
      - name: vehicle_count
        description: "车辆数"
        meta:
          column_name_cn: "车辆数"
      - name: normal_rate
        description: "正常交易率"
        meta:
          column_name_cn: "正常交易率"
    meta:
      table_name_cn: "日收费收入汇总表"
      business_domain: "收费业务"
      data_source: "收费系统"
      update_frequency: "日"
      owner: "收费中心"
      
  - name: dws_traffic_flow_daily
    description: "日车流量汇总，按日期、收费站、时段等维度汇总车流量"
    columns:
      - name: transaction_date
        description: "交易日期"
        meta:
          column_name_cn: "交易日期"
      - name: station_id
        description: "收费站ID"
        meta:
          column_name_cn: "收费站ID"
      - name: total_vehicles
        description: "总车流量"
        meta:
          column_name_cn: "总车流量"
      - name: unique_vehicles
        description: "唯一车辆数"
        meta:
          column_name_cn: "唯一车辆数"
      - name: time_period
        description: "时段分类"
        meta:
          column_name_cn: "时段分类"
    meta:
      table_name_cn: "日车流量汇总表"
      business_domain: "收费业务"
      data_source: "收费系统"
      update_frequency: "日"
      owner: "收费中心"
      
  - name: dws_station_performance_daily
    description: "收费站日绩效汇总，收费站维度的综合绩效指标"
    columns:
      - name: transaction_date
        description: "交易日期"
        meta:
          column_name_cn: "交易日期"
      - name: station_id
        description: "收费站ID"
        meta:
          column_name_cn: "收费站ID"
      - name: total_revenue
        description: "日收入（元）"
        meta:
          column_name_cn: "日收入"
      - name: normal_rate
        description: "正常交易率"
        meta:
          column_name_cn: "正常交易率"
      - name: data_quality_rate
        description: "数据质量率"
        meta:
          column_name_cn: "数据质量率"
      - name: etc_rate
        description: "ETC使用率"
        meta:
          column_name_cn: "ETC使用率"
    meta:
      table_name_cn: "收费站日绩效汇总表"
      business_domain: "收费业务"
      data_source: "收费系统"
      update_frequency: "日"
      owner: "收费中心"

